name: PR Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup-pr-deployment:
    runs-on: ubuntu-latest
    name: Cleanup PR Deployment
    # Skip execution on template repository or when PR is not closed
    if: github.repository != 'Artificer-Innovations/aws-static-site-pr-deployment' && (github.event.pull_request.merged == true || github.event.pull_request.merged == false)

    steps:
      - name: Check deployment configuration
        run: |
          echo "🔧 Checking deployment configuration..."

          MISSING_CONFIG=()

          # Check required secrets
          [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && MISSING_CONFIG+=("AWS_ACCESS_KEY_ID (secret)")
          [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] && MISSING_CONFIG+=("AWS_SECRET_ACCESS_KEY (secret)")

          # Check required variables
          [ -z "${{ vars.AWS_REGION }}" ] && MISSING_CONFIG+=("AWS_REGION (variable)")
          [ -z "${{ vars.S3_BUCKET_NAME }}" ] && MISSING_CONFIG+=("S3_BUCKET_NAME (variable)")
          [ -z "${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}" ] && MISSING_CONFIG+=("CLOUDFRONT_DISTRIBUTION_ID (variable)")

          if [ ${#MISSING_CONFIG[@]} -gt 0 ]; then
            echo "❌ Missing required configuration:"
            printf "   • %s\n" "${MISSING_CONFIG[@]}"
            echo ""
            echo "📝 This is a template repository. To configure deployment:"
            echo "   1. Go to Settings > Secrets and variables > Actions"
            echo "   2. Add the missing secrets and variables listed above"
            echo "   3. See docs/GITHUB-SETUP.md for detailed instructions"
            exit 1
          fi

          echo "✅ All required configuration found, proceeding with cleanup..."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Clean up PR deployment folder
        run: |
          PR_FOLDER_NAME="pr-${{ github.event.pull_request.number }}"
          echo "Cleaning up PR deployment folder: ${PR_FOLDER_NAME}"

          # Check if the folder exists before trying to delete
          if aws s3 ls "s3://${{ vars.S3_BUCKET_NAME }}/${PR_FOLDER_NAME}/" >/dev/null 2>&1; then
            echo "Deleting S3 folder: s3://${{ vars.S3_BUCKET_NAME }}/${PR_FOLDER_NAME}/"
            aws s3 rm "s3://${{ vars.S3_BUCKET_NAME }}/${PR_FOLDER_NAME}/" --recursive

            # Create CloudFront invalidation to clear cache
            echo "Creating CloudFront invalidation for cleanup..."
            aws cloudfront create-invalidation \
              --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
              --paths "/${PR_FOLDER_NAME}/*" >/dev/null || true

            echo "✅ PR deployment folder ${PR_FOLDER_NAME} cleaned up successfully"
          else
            echo "ℹ️ PR deployment folder ${PR_FOLDER_NAME} not found, nothing to clean up"
          fi

      - name: Comment cleanup status
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
            const message = '${{ job.status }}' === 'success'
              ? `PR deployment folder \`pr-${{ github.event.pull_request.number }}\` has been cleaned up from S3`
              : `Failed to clean up PR deployment folder \`pr-${{ github.event.pull_request.number }}\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 **PR Cleanup:** ${status} ${message}`
            })
